# Generated by Django 6.0.5 on 2026-06-24 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fuel_types',
            field=models.CharField(default='Petrol,Diesel,Gas', max_length=255),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_type_entries', to='api.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
